library("zoo")
library("PerformanceAnalytics")
library("xts")
valueFile <- "~/ShinyApps/tosAsync/out/value.csv"
data <- read.csv(valueFile)
data.zoo <- read.zoo(valueFile,format="%Y-%m-%d %H:%M:%S", header=T, sep=",")
data.xts <- as.xts(data.zoo)
data.zoo$all <- rowSums(data.zoo)
plot(data.zoo)
plot.zoo(data.xts)
#plot.zoo(data$all)
#chart.TimeSeries(data$roll )
chart.CumReturns(data.zoo$roll, wealth.index=T)
